### ISSUE TITLE
[BUG] 게시글 생성 페이지 수정

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#102]
## 🌴 작업 브랜치 

`fix-post_creation_bug`

## 🐛 BUG 개요 

- api 변경되어 기존에 이미지 key값을 images -> files로 변경된 에러
- 해설 게시글 년도, 회차 데이터 값 변경에 따른 에러

## ✅ TODO 및 진행현황 

- [x] api 변경되어 기존에 이미지 key값을 images -> files로 변경된 에러
- [x] 해설 게시글 년도 데이터 값 변경에 따른 에러 처리
- [x] 해설 게시글 회차 데이터 값 변경에 따른 에러 처리
- [x] 해설 게시글 제목 작성하지 않을시 경고 문구
- [x] 해설 게시글 입력 번호가 전체 문제 갯수를 넘어갈 경우 경고 문구
- [x] 해설 게시글 예외에 따라 submit 제출되지 않도록 구현 
--------------------------------------------------------------------------
- [x] 꿀팁 게시글
