### ISSUE TITLE
[BUG] 체점 에러

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#117]
## 🌴 작업 브랜치 

`fix/grading-error`

## 🐛 BUG 개요 

2. 체출버튼을 누르지 않았는데 제출되는 문제가 발생하였습니다.
3. 초기화를 하지 않아 다시 문제를 풀때 해당 데이터가 그대로 남아있는 문제가 발생하였습니다.
4. 제출되고 다시 문제를 풀면 1번부터 시작해야하는데, 마지막에 머문 번호로 이동됩니다.
5. 타이머가 다시 문제를 풀었을 때 동작되지 않는 문제가 발생하였습니다.
6. 결과페이지가 제대로 동작되지 않는 문제가 발생했습니다.
7. 선택된 답듵이 다 0처리되는 문제가 발생했습니다.
8. 문제를 이동시킬때 머문시간을 체크하지 않는 문제가 발생하였습니다.
9. 문제를 다시 풀 때 `Qustion.tsx`의 `resetOptionOnReclick()`에서 무한루프가 발생하는 문제가 발생하였습니다.

## 🚧 BUG 리포트 

2. 제출하는 `useEffect`코드에 `subjectResultList`의 값이 채워져 있으면 제출하도록 기존에 코드가 작성되어있었고, 제출 후 `subjectResultList`를 초기화하지 않아 기존의 값이 있는 상태가 유지되어서, 랜더링 될 때마다 제출되는 문제가 발생하였고, 제출하기, 확인 버튼을 클릭할 경우에 `subjectResultList`와 `userAnswerList`를 초기화해주는 작업을 진행했습니다.
3. 그만두기, 제출하기, 확인 버튼을 클릭시 `subjectResultList`, `userAnswerList`를 `[]`로 초기화하였습니다.

4. `userAnswer`, `questionIdx`를 초기화하지 않아서 발생한 문제로 그만두기, 제출하기, 확인버튼을 클릭할 경우에 `userAnswer`, `questionIdx`를 초기화하여 다시 문제를 풀 때 1번 부터 풀 수 있도록 초기화해주었습니다.
5. 모달창들을 오픈했을 때, 모달창들을 닫을 때는 `setIsPausedTimer(false)` 모달창 제출하기를 눌렀을때, 모달창 확인버튼을 눌렀을 때는 `setIsPausedTimer(true)` 모의고사를 시작할 때는 `setIsPausedTimer(false)` 코드를 추가하여 타이머가 정상작동되도록 수정하였습니다.
6. 결과페이지는 따로 브랜치를 파서 수정할 예정입니다.
7. 2번을 해결하는 과정에서 useEffect의 조건을 설정하지 않아 계속 제출되는 에러가 발생하여 제출하기 버튼을 누를 때, 바로`setUserAnswerList([]);`  `setSubjectResultList([]);` 를 해주었는데, 이렇게 설정하니 기존에 클릭했던 정보들이 싹 날라가는 문제가 발생하게 되었었고, 이 코드를 제출하기 버튼을 눌렀을 때 발생시키지 않도록 제거하고 제출 post가 된 다음 그 응답으로 순서를 변경하여 문제를 해결하였습니다.
8. `recordSessionTime()` 함수를 `AllQuestionModalProps`로 전달하여 문제 클릭시 머문시간을 기록할 수 있도록 수정하였습니다.
9. 기존 코드에서는 `userAnswer.selectOptionSeq === userAnswerList[questionIdx]?.selectOptionSeq`만 같으면 `setUserAnswer의 selectOptionSeq`를 0으로 초기화하는 로직이어서, 처음 시작 시 `resetOptionOnReclick` 함수에서 `userAnswer.selectOptionSeq`가 0이고 이 번호가 존재하면 `userAnswerList[questionIdx]?.selectOptionSeq`를 0으로 업데이트 하게 되고, `userAnswer.selectOptionSeq`와 `userAnswerList[questionIdx]?.selectOptionSeq`가 0으로 동일하기 때문에 또, `userAnswer.selectOptionSeq === userAnswerList[questionIdx]?.selectOptionSeq`가 같게 되고 또 0으로 되고 이런 무한루프가 발생하여 무한루프 에러가 발생하였습니다. 따라서 `resetOptionOnReclick` 함수의 원래 의도대로 0이 아닌 똑같은 번호를 다시 클릭하였을 때 0으로 초기화하여 클릭하지 않은 상태로 만드는 함수로 만들기 위해 `userAnswerList[questionIdx]?.selectOptionSeq !== 0 && userAnswer.selectOptionSeq !== 0`의 조건을 추가해주었습니다. 

## ✅ TODO 및 진행현황 

- [x] 체출버튼을 누르지 않았는데 제출되는 문제가 발생하였습니다.
- [x] 초기화를 하지 않아 다시 문제를 풀때 해당 데이터가 그대로 남아있는 문제가 발생하였습니다.
- [x] 제출되고 다시 문제를 풀면 1번부터 시작해야하는데, 마지막에 머문 번호로 이동됩니다.
- [x] 타이머가 다시 문제를 풀었을 때 동작되지 않는 문제가 발생하였습니다.
- [x] 결과페이지가 제대로 동작되지 않는 문제가 발생했습니다.
- [x] 선택된 답듵이 다 0처리되는 문제가 발생했습니다.
- [x] 문제를 이동시킬때 머문시간을 체크하지 않는 문제가 발생하였습니다.
- [x] 문제를 다시 풀 때 `Qustion.tsx`의 `resetOptionOnReclick()`에서 무한루프가 발생하는 문제가 발생하였습니다.
