### ISSUE TITLE
[BUG] 게시글 상세페이지 api 변경에 따른 수정

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#127]
## 🌴 작업 브랜치 

`fix_community-detail`

## 🐛 BUG 개요 

- api가 변경됨에 따라 에러가 발생

## ✅ TODO 및 진행현황 

- [x] api url 변경
- [x] 데이터 변경 값 반영
- [x] 백엔드 수정 요청(댓글 달아지지 않는 에러 발생)
