### ISSUE TITLE
[BUG] 온보딩 페이지 우선순위 설정 에러

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#128]
## 🌴 작업 브랜치 

`fix-cert_priority_bug`

## 🐛 BUG 개요 

- 온보딩 페이지 우선순위 설정하는 부분에서 POST에러가 발생하고 있습니다. (이미 POST가 되었다는 500에러 발생)

## 🚧 BUG 리포트 

- 백엔드에서 어떤 문제가 발생했던 것 같습니다.

## ✅ TODO 및 진행현황 

- [x] 프로필 설정 페이지 확인
- [x] 자격증 선택 페이지 확인
- [x] 자격증 우선순위 설정 페이지 확인
