### ISSUE TITLE
[FEATURE] 헤더 기능 구현

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#132]
## 🌴 작업 브랜치 

`feature_second-header`

## 💼 TASK 개요 

<img width="857" alt="image" src="https://github.com/COS-project/cos-frontend/assets/156565796/f4541245-8b56-483f-8f32-46e5e0bb461b">
- 헤더 기능을 구현합니다. (기존 헤더에서 렌더링 변경)

## ✅ TODO 및 진행현황 

- [x] 자격증을 선택할 수 있는 기능 구현
- [x] 헤더 퍼블리싱 및 render 코드 수정
- [x] 응시 정보 경로 연결
