### ISSUE TITLE
[BUG] 모의고사 결과 페이지 averageSubjectList 에러 수정 

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#158]
## 🌴 작업 브랜치 

`fix/error-on-mockExam-page`

## 🐛 BUG 개요 

1. TotalTakenTime 정의되지 않았다는 에러 발생
2. 모의고사를 시작할 때 제출이 한번 더 되는 에러가 발생 총 요청이 2번 가지는 현상.
3. 모의고사를 응시한 다음 그 결과가 바로 떠야하는데 그 전 결과가 뜨는 에러 발생
4. 모의고사가 전체 중의 비율로 나타나지지 않는 스타일적 문제가 발생

## 🚧 BUG 리포트 

1. `const sumTotalTakenTime = () => {
    if (examResults) {
      examResults[examResults.length - 1]?.subjectResults.map((subjectResult) => {
        totalTakenTime += subjectResult.totalTakenTime;
      });
      return totalTakenTime;
    } else {
      return 0;
    }
  };`

에서
examResults가 빈리스트 인지 판단하고 `examResults.length > 0`
`subjectResults?.reduce((acc, curr) => acc + (curr.totalTakenTime || 0), 0) || 0;`
로 변경

2. TestSubmitOrCancle.tsx 폴더의 
` useEffect(() => {
    if (timeLeft <= 0) {
      setIsRunning(false);
      setIsAutoSubmitTimeUpModalOpen(!isAutoSubmitTimeUpModalOpen);
    }
  }, [timeLeft]);`

setIsRunning(false); 로 isRunning값을 false로 만들어 두고 모의고사가 완료되었음에도 불구하고 그대로 냅둬서
새로 모의고사를 시작할 때
`useEffect(() => {
    if (!isRunning) {
      recordSessionTime();
      setSessionRecorded(true); //바로 다음 useEffect 실행시키기 위한 트릭
    }
  }, [isRunning]);`
부분이 실행되어 두번 요청되는 문제가 발생하였음.

`useEffect(() => {
    if (!isRunning) {
      recordSessionTime();
      setSessionRecorded(true); //바로 다음 useEffect 실행시키기 위한 트릭
      setIsRunning(true); //시작할 때 제출되는 것을 막기위함.
    }
  }, [isRunning]);`
isRunning값을 true로 바꿨음

3. router를 데이터가 다 불러와진 상태에서 했어야했는데 불러와지지 않고 Router로 페이지를 이동시켜 그 전 데이터가 먼저 불러와지고 그 후에 새로운 데이터가 불러와져서 생긴 오류 -> router를 .then()함수에 넣어 모든 일이 처리된 다음 불러오도록하여 순서를 정리시킴

4. 높이 값을 `height={millisecondsToMinutes(subjectResult.totalTakenTime)} `에서 `height={(subjectResult.totalTakenTime / timeLimit) * 100}` 로 변경

## ✅ TODO 및 진행현황 

- [x] TotalTakenTime 정의되지 않았다는 에러 발생
- [x] 모의고사를 시작할 때 제출이 한번 더 되는 에러가 발생 총 요청이 2번 가지는 현상.
- [x] 모의고사를 응시한 다음 그 결과가 바로 떠야하는데 그 전 결과가 뜨는 에러 발생
- [x] 모의고사가 전체 중의 비율로 나타나지지 않는 스타일적 문제가 발생
