### ISSUE TITLE
[BUG] 모의고사 홈페이지 기능 수정

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#160]
## 🌴 작업 브랜치 

`fix/modify-mockexam-homepage`

## 🐛 BUG 개요 

1. 필터 default 값 2017년도에서 불러오는 데이터로 변경
2. 랜덤 모의고사 이동하는 부분 모달창 처리
3. 0점일 경우에 성적리포트 안보이는 문제 해결
4. 필터 위치 변경

## 🚧 BUG 리포트 

1.
```
const [isFirstRender, setIsFirstRender] = useState(true);

  useEffect(() => {
    if (examYears && isFirstRender) {
      setSelectedYear(examYears[0]);
      setIsFirstRender(false);
    }
  }, [examYears]);
```
2. RandomMockExamModal.tsx 구현
3. 
`{examResults && examResults[examResults?.length - 1]?.totalScore ? (` 에서
`{examResults  ? (`으로 변경
4. `top-[45%] `으로 변경

## ✅ TODO 및 진행현황 

- [x] 필터 default 값 2017년도에서 불러오는 데이터로 변경
- [x] 랜덤 모의고사 이동하는 부분 모달창 처리
- [x] 0점일 경우에 성적리포트 안보이는 문제 해결
- [x] 필터 위치 변경
