### ISSUE TITLE
[BUG] 커뮤니티 페이지 에러

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#166]
## 🌴 작업 브랜치 

`fix-community_page_error`

## 🐛 BUG 개요 

- 커뮤니티 페이지의 userPostsList, commentarySearchResults에 빈 배열이 올 경우 이를 처리하지 않아 에러가 발생하였습니다.
- 모달 페이지 위치를 변경
- 필터 위치 변경

## ✅ TODO 및 진행현황 

- [x] 커뮤니티 페이지의 userPostsList, commentarySearchResults에 빈 배열이 올 경우 이를 처리하지 않아 에러가 발생하였습니다.
- [x] 모달 페이지 위치를 변경
- [x] 필터 위치 변경
