### ISSUE TITLE
[FEATURE] 스톱워치 기능 추가 구현 

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#168]
## 🌴 작업 브랜치 

`feature/extend-stopwatch-functionality`

## 💼 TASK 개요 

스톱워치 기능을 이어서 구현합니다.
- 기존에 한곳에 모여있던 컴포넌트들을 분리합니다.
- style이 디자인과 다른 곳을 수정합니다.
- post api를 연결합니다.

## ✅ TODO 및 진행현황 

- [x] 기존에 한곳에 모여있던 컴포넌트들을 분리합니다
- [x] style이 디자인과 다른 곳을 수정합니다
- [x] post api를 연결합니다
