### ISSUE TITLE
[FEATURE] onboarding page publishing

### ISSUE THREAD

**Issue by unnimm** [COS-project/cos-frontend#2]
## 🌴 작업 브랜치 
`yurim`
( 컨벤션 확인을 뒤늦게 했습니다..😭 )

## 💼 TASK 개요 

온보딩 페이지 퍼블리싱
- 관심 자격증 설정
- 관심 자격증 설정 후 우선순위 설정

## ✅ TODO 및 진행현황 

- [x] 유저별 관심 자격증 체크
- [x] 유저별 관심 자격증 우선순위 설정
- [x] CertificationClassificationItem 컴포넌트 생성
- [x] fimga svg 아이콘 적용
