### ISSUE TITLE
[FEATURE] mainpage 컴포넌트 개발 및 기존 컴포넌트 병합

### ISSUE THREAD

**Issue by Choguesung** [COS-project/cos-frontend#24]
## 🌴 작업 브랜치 

feature-mainpage_new

## 💼 TASK 개요 

메인페이지에서 사용될 새로운 컴포넌트 개발과 기존 사용되던 컴포넌트 병합하기

## ✅ TODO 및 진행현황 

- [ ] 인삿말 카드 기능 개발
- [x] 목표달성 카드 기능 개발
- [x] 오늘 목표 카드 기능 개발
- [x] 성장 그래프 기능 개발
- [ ] 베스트 꿀팁 기능 개발
