### ISSUE TITLE
[FEATURE] feat-exam_info 응시 정보 페이지 구현

### ISSUE THREAD

**Issue by unnimm** [COS-project/cos-frontend#4]
## 🌴 작업 브랜치 
`feat-exam_info`

## 💼 TASK 개요 

**자격증 종류별로 응시 정보 페이지를 구현합니다.**
- 응시 정보에는 자격증 소개, 시험 일정, 시험 과목, 응시료, 시험 방식, 응시 자격, 합격 기준이 있습니다.
- utils 폴더에 파일을 생성하여 데이터를 저장할 예정입니다.
- 선택된 자격증 별로 다른 자격증 정보를 보여줄 수 있도록 기능을 구현할 예정입니다.
- 해당 페이지에서는 Navbar가 사라지게 하며, background가 gray0색으로 변하게 할 예정입니다.

## ✅ TODO 및 진행현황 

- [x] ExamInfo 컴포넌트 만들기
- [x] utils에 각 자격증 별 데이터 생성 (객체 타입)
- [x] 홈 화면에서 해당 페이지로 이동되도록 버튼 생성 (해당 버튼도 컴포넌트로 만들기)
- [x] 해당 페이지에 Navbar 없애기
- [x] 해당 페이지에 bg-gray0으로 변경
