### ISSUE TITLE
[FEATURE] 해설 게시판 상세내용 API 연동

### ISSUE THREAD

**Issue by ruluralaa** [COS-project/cos-frontend#46]
## 🌴 작업 브랜치 
feature-publish_community_detail

## 💼 TASK 개요 
백엔드 api를 이용하여 데이터를 주고 받습니다.

## ✅ TODO 및 진행현황 

- [x] 상세페이지 네비게이션 바
- [x] 댓글 양식(댓글)
- [x] 댓글 양식(대댓글)
- [x] 프로필
- [x] 태그
- [x] 댓글 작성칸
- [x] 따봉 아이콘
- [x] 포스트(제목, 글, 사진)
