### ISSUE TITLE
[FEATURE] 프로필 설정 퍼블리싱 및 기능 구현

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#52]
## 🌴 작업 브랜치 
`feature/onboarding-profile-setup`

## 💼 TASK 개요 

온보딩 페이지에서 api get요청을 보내 카카오 프로필을 불러오고 fetch로 닉네임과 프로필을 설정할 수 있도록 합니다.

## ✅ TODO 및 진행현황 

- [x] 프로필 설정 퍼블리싱
- [x] 프로필 설정 api get요청
- [x] 프로필 설정 api fetch요청
