### ISSUE TITLE
[FEATURE] main_page 기능 구현

### ISSUE THREAD

**Issue by Choguesung** [COS-project/cos-frontend#75]
## 🌴 작업 브랜치 

feature-main_home

## 💼 TASK 개요 

메인 페이지 퍼블리싱 및 기능 구현

## ✅ TODO 및 진행현황 

- [x] 목표 달성 카드 구현
- [x] 오늘 목표 카드 구현
- [x] 성장 그래프 카드 구현
- [x] 과목별 정답률 카드 구현
- [x] 머문시간 그래프 카드 구현
