### ISSUE TITLE
[FEATURE] 따끈따끈 후기 퍼블리싱

### ISSUE THREAD

**Issue by ruluralaa** [COS-project/cos-frontend#8]
## 🌴 작업 브랜치 
feature-publish_community

## 💼 TASK 개요 
따끈따끈 후기 게시판 상세페이지를 퍼블리싱합니다.

## ✅ TODO 및 진행현황 

- [ ] 기본 화면 퍼블리싱
- [ ] 시험 목표 및 시험 후기 작성하기 퍼블리싱
- [ ] 시험 목표 설정 모달 퍼블리싱
- [ ] 시험 후기 작성 모달 퍼블리싱
- [ ] 사용자가 설정한 난이도와 준비기간 뜨도록 표시
