### ISSUE TITLE
[BUG] 온보딩 버그 수정 및 변경된 서버에 맞게 변경

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#90]
## 🌴 작업 브랜치 
`bug-onboarding`

## 🐛 BUG 개요 

- 닉네임 , 프로필 설정이 post되지 않는 에러 발생
- 관심자격증 설정 부분 데이터 형식 변경된 대로 데이터 수정
- 프로필을 설정하지 않고 닉네임만 변경하는 경우 에러 -> 백엔드 요청

## ✅ TODO 및 진행현황 

- [x] 닉네임 , 프로필 설정이 post되지 않는 에러 해결
- [x] 관심자격증 설정 부분 데이터 형식 변경된 대로 데이터 수정
- [x] 프로필을 설정하지 않고 닉네임만 변경하는 경우 에러 -> 백엔드 요청
