### ISSUE TITLE
[BUG] 목표 설정 수정

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#92]
## 🌴 작업 브랜치 
`bug-goal_setting`

## 🐛 BUG 개요 

- 기존에 초기화 버튼을 모달창으로 변경하여 수정
- 목표 수정하는 부분 API 에러가 발생

## ✅ TODO 및 진행현황 

- [x] 목표를 새로 설정하는 부분과 기존 목표를 수정
- [x] 변경된 API에 맞게 데이터 값을 수정
- [x] put 수정 에러
