### ISSUE TITLE
[BUG] 모의고사 시험응시 페이지 에러 수정

### ISSUE THREAD

**Issue by ummiih** [COS-project/cos-frontend#93]
## 🌴 작업 브랜치 

`bug-mock_exam_test`

## 🐛 BUG 개요 

- API 데이터 형식이 수정되어서 에러가 발생되었습니다.
- 취소하기, 저장하기를 눌렀을 때 각각 모달창이 뜨도록 디자인이 변경되었습니다.
- 시험 응시 시간이 종료되었을 때 저장되는 기능이 누락되었습니다.
- 글자가 깨지면 네모 박스를 넘어가는 버그가 발생하였습니다.

## ✅ TODO 및 진행현황 

- [x] API 데이터 형식값에 따라 수정
- [x] 취소하기, 저장하기 모달창
- [x] 시험 응시 시간 종료될 시 저장
- [x] 글자 깨질경우 네모 박스 넘어가는 CSS스타일 잡기
